version: "3.6"

services:
  api:
    image: notification-hub/api/release
    restart: "no"
    ports:
      - 3000:3000
    environment:
      ACCESS_TOKENS: ${ACCESS_TOKENS?}
      AMQP_URL: amqp://hub:${RABBITMQ_PASSWORD?}@rabbitmq:5672
      AMQP_QUEUE: notifications
      LOG_LEVEL: debug
      LOG_NAME: notification-hub-api
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000
      SERVER_SIZE_LIMIT: 1mb
