version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3.7.18-management
    restart: "no"
    hostname: "rabbitmq"
    ports:
      - ${AMQP_PORT:-5672}:5672
      - ${AMQP_API_PORT:-15672}:15672
    environment:
      - hostname=rabbitmq
      - RABBITMQ_DEFAULT_USER=hub
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD?}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  runner:
    image: registry.gitlab.com/7egend/projects/home/microservices/notification-hub/server/runner:2.0.2
    restart: "no"
    environment:
      AMQP_URL: amqp://hub:${RABBITMQ_PASSWORD?}@rabbitmq:5672
      AMQP_QUEUE: notifications
      AZURE_ORG_URL: ${AZURE_ORG_URL?}
      AZURE_ACCESS_TOKEN: ${AZURE_ACCESS_TOKEN?}
      LOG_LEVEL: debug
      LOG_NAME: notification-hub-runner
      SLACK_ACCESS_TOKEN: ${SLACK_ACCESS_TOKEN?}

volumes:
  rabbitmq-data:
