# -------------------------------------
# Gateway
# -------------------------------------
gateway_traefik_docker_image: traefik:v2.8.8
gateway_network: gateway
gateway_traefik_http_port: 80
gateway_traefik_https_port: 443

# -------------------------------------
# Notification Hub
# -------------------------------------
notification_hub_runner_docker_image: registry.gitlab.com/7egend/projects/home/microservices/notification-hub/server/runner
notification_hub_runner_docker_image_tag: "{{ general_tag }}"
notification_hub_api_docker_image: registry.gitlab.com/7egend/projects/home/microservices/notification-hub/server/api
notification_hub_api_docker_image_tag: "{{ general_tag }}"

# -------------------------------------
# AMQP
# -------------------------------------
amqp_rabbitmq_docker_image: rabbitmq:3.11.7-management
amqp_rabbitmq_port: 5672
amqp_rabbitmq_management: 15672
