# -------------------------------------
# Copy application files to target.
# -------------------------------------
- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ notification_hub_project_src }}"
    state: directory
    recurse: yes

- name: Render docker-compose.yaml file
  ansible.builtin.template:
    src: docker-compose.yaml
    dest: "{{ notification_hub_project_src }}/docker-compose.yaml"
    mode: u=rx

- name: Copy .env file
  ansible.builtin.copy:
    src: .env
    dest: "{{ notification_hub_project_src }}/.env"
    mode: '0644'

# -------------------------------------
# Login so we can pull missing images.
# -------------------------------------
- name: Log into docker registry
  community.docker.docker_login:
    registry_url: "{{ gitlab_registry_url }}"
    username: "{{ gitlab_username }}"
    password: "{{ gitlab_password }}"

# -------------------------------------
# Restart services and check if they
# are running.
# -------------------------------------
- name: Start new services and recreate existing ones
  community.docker.docker_compose:
    project_src: "{{ notification_hub_project_src }}"
    restarted: yes
    recreate: always
    state: present
    remove_orphans: yes

# -------------------------------------
# Log out.
# -------------------------------------
- name: Log out from registry
  community.docker.docker_login:
    registry_url: "{{ gitlab_registry_url }}"
    state: absent
    
