# -------------------------------------------------
# More info at:
# https://gitlab.com/7egend/projects/home/devops/pipelines/templates
# -------------------------------------------------
include:
 - project: 7egend/projects/home/devops/pipelines/templates
   ref: main
   file:
     - /buildx/gitlab-ci.yml
     - /deploys/deployment.yml
     - /deploys/notify.yml

variables:
  SLACK_TYPE: slack-channel-members
  SLACK_CHANNEL: devops

stages:
  - prepare
  - build
  - test
  - release
  - release:notify
  - deploy
  - deploy:notify


# ----------------------------------------------------------------------------------------
# Deployments
# ----------------------------------------------------------------------------------------
deploy:notification-hub:runner:
  extends: .deploy
  variables:
    DEPLOYER_MANEGEMENT_IMAGE: registry.gitlab.com/7egend/projects/home/microservices/notification-hub/devops/ansible:latest
    PLAYBOOK: playbooks/production/notification-hub/deploy.yaml
    DOCKER_VERSION_VARIABLE: notification_hub_runner_docker_image
    DOCKER_VERSIONS_FILE: group_vars/production/docker.yaml

deploy:notification-hub:api:
  extends: .deploy
  variables:
    DEPLOYER_MANEGEMENT_IMAGE: registry.gitlab.com/7egend/projects/home/microservices/notification-hub/devops/ansible:latest
    PLAYBOOK: playbooks/production/notification-hub/deploy.yaml
    DOCKER_VERSION_VARIABLE: notification_hub_api_docker_image
    DOCKER_VERSIONS_FILE: group_vars/production/docker.yaml


# ----------------------------------------------------------------------------------------
# Slack Notifications
# ----------------------------------------------------------------------------------------
deploy:notification-hub:runner:notify:success:
  extends: .deploy:notify:success
  variables:
    PROJECT_TITLE: server/runner
    ENVIRONMENT_NAME: production
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'trigger' && $DEPLOY_TARGET == 'deploy:notification-hub:runner'"

deploy:notification-hub:api:notify:success:
  extends: .deploy:notify:success
  variables:
    PROJECT_TITLE: server/api
    ENVIRONMENT_NAME: production
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'trigger' && $DEPLOY_TARGET == 'deploy:notification-hub:api'"
