version: "3.6"

services:
  runner:
    image: notification-hub/runner/release
    restart: "no"
    environment:
      AMQP_URL: amqp://${RABBITMQ_USERNAME:-runner}:${RABBITMQ_PASSWORD?}@rabbitmq:5672
      AMQP_QUEUE: notifications
      AZURE_ORG_URL: ${AZURE_ORG_URL?}
      AZURE_ACCESS_TOKEN: ${AZURE_ACCESS_TOKEN?}
      LOG_LEVEL: debug
      LOG_NAME: notification-hub-runner
      SLACK_ACCESS_TOKEN: ${SLACK_ACCESS_TOKEN?}
