version: '3.5'

services:
  traefik:
    image: '{{ gateway_traefik_docker_image }}'
    ports:
      # HTTP and HTTPS
      - '{{ gateway_traefik_http_port }}:80'
      - '{{ gateway_traefik_https_port }}:443'
      # Dashboard (should not be public)
      - 127.0.0.1:8080:8080
    volumes:
      # Volume to persistenly store Let's Encrypt certificates.
      # Certificate files should live throught restarts so we don't
      # hit the Let's Encrypt rate limits.
      - traefik-certificates:/letsencrypt

      # Static traefik configuration. Contains endpoints & providers
      # definitions and properties.
      - ./traefik/static.toml:/etc/traefik/traefik.toml:ro

      # Dynamic configuration. Declares all available routers, services
      # and middlewares.
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    mem_limit: 200m
    mem_reservation: 100m
    restart: always
    networks:
        - '{{ gateway_network }}'

volumes:
  traefik-certificates:

networks:
  {{ gateway_network }}:
      external: true
