name: Build server/api docker image

on:
  workflow_dispatch:
  push:
   branches:    
     - main
   tags:
     - '*.*.*'
   paths:
     - 'server/api/**'

jobs:
  build-image:
    uses: 7egend/workflows/.github/workflows/build.yml@main
    permissions: write-all
    secrets: inherit
    with:
      CONTEXT_PATH: server/api/
