name: Build server/runner docker image

on:
  workflow_dispatch:

jobs:
  build-image:
    uses: 7egend/workflows/.github/workflows/build.yml@main
    permissions: write-all
    secrets: inherit
    with:
      DOCKERFILE_PATH: server/runner/Dockerfile
      CONTEXT_PATH: server/runner
