name: Build server/runner docker image

on:
  workflow_dispatch:
  push:
    branches:    
      - main
    tags:
      - '*.*.*'
    paths:
      - 'devops/ansible/**'
      
jobs:
  build-image:
    uses: 7egend/workflows/.github/workflows/build.yml@main
    permissions: write-all
    secrets: inherit
    with:
      DOCKERFILE_PATH: devops/ansible/Dockerfile
      CONTEXT_PATH: devops/ansible
