on:
  workflow_call:
    inputs:
      SLACK_CHANNEL:
        description: The Slack channel name to post the notification
        type: string
        required: true
      AUTHOR_NAME:
        description: The author's fullname that triggered the deployment
        type: string
        required: true
      CREATED_AT:
        description: 'The date of commit that triggered the deployment (format: YYYY-MM-DDTHH:mm:ss.xxxZ)'
        type: string
        required: true
      ENVIRONMENT:
        description: The target environment of the deployment
        type: string
        required: true
      PROJECT_NAME:
        description: The project name
        type: string
        required: true
      WORKGROUP:
        description: The subproject path that triggered the deployment
        type: string
        required: true
      RELEASE_TAG:
        description: The deployed release tag
        type: string
        required: true
      RELEASE_CHANGELOG:
        description: The changelog of the release
        type: string
        required: true
      LINKS_SOURCE_CODE:
        description: The url of the repository that triggered the deployment
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Posting successful deployment notification
      run: |
        curl -X POST "https://hub.7egend.cr/v1/notifications" \
          -H "Authorization: Bearer ${{ secrets.NOTIFICATION_HUB_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "platforms": [
                  {
                    "type": "slack-channel-members",
                    "channel": "${{ inputs.SLACK_CHANNEL }}"
                  }
                ],
                "notification": {
                  "type": "SuccessfulDeployment",
                  "author": "${{ inputs.AUTHOR_NAME }}",
                  "createdAt": "${{ inputs.CREATED_AT }}",
                  "environment": "${{ inputs.ENVIRONMENT }}",
                  "group": "${{ inputs.PROJECT_NAME }}",
                  "subgroup": "${{ inputs.WORKGROUP }}",
                  "release": {
                    "tag": "${{ inputs.RELEASE_TAG }}",
                    "changelog": "${{ inputs.RELEASE_CHANGELOG }}"
                  },
                  "links": {
                    "sourceCode": "${{ inputs.LINKS_SOURCE_CODE }}"
                  }
                }
              }'
