on:
  workflow_call:
    inputs:
      SLACK_EMAIL:
        description: The slack user's email to post the notificatoin
        type: string
        required: true
      PROJECT_NAME:
        description: The project name
        type: string
        required: true
      LINKS_SOURCE_CODE:
        description: The url of the repository that tried to build the Docker image
        type: string
        required: true
      LINKS_IMAGE:
        description: The failed Docker image url
        type: string
        required: true
      LINKS_PIPELINE:
        description: The pipeline url that failed to build the Docker image
        type: string
        required: true
      LINKS_REGISTRY:
        description: The registry url that contains all Docker images
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Posting failed Docker image notification
      run: |
        curl -X POST "https://hub.7egend.cr/v1/notifications" \
          -H "Authorization: Bearer ${{ secrets.NOTIFICATION_HUB_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "platforms": [
                  {
                    "type": "slack-member-email",
                    "email": "${{ inputs.SLACK_EMAIL }}"
                  }
                ],
                "notification": {
                  "type": "FailedDockerImage",
                  "group": "${{ inputs.PROJECT_NAME }}",
                  "links": {
                    "sourceCode": "${{ inputs.LINKS_SOURCE_CODE }}",
                    "pipeline": "${{ inputs.LINKS_PIPELINE }}",
                    "registry": "${{ inputs.LINKS_REGISTRY }}",
                    "image": "${{ inputs.LINKS_IMAGE }}"
                  }
                }
              }'
