on:
  workflow_call:

jobs:
  build-and-publish-npm-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/nodejs/models
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn run build

      - name: Set package version
        run: npm version test --no-git-tag-version

      - name: Publish to NPM registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-new-npm-package-version-notification:
    uses: 7egend/workflows/.github/workflows/notification-hub-post-new-npm-package-version.yml@main
    secrets: inherit
    needs: build-and-publish-npm-package
    with:
      SLACK_CHANNEL: hub
      AUTHOR_NAME: Tiago Barros
      PROJECT_NAME: Hub
      RELEASE_TAG: test
      RELEASE_CHANGELOG: Hardcoded
      LINKS_SOURCE_CODE: "https://7egend.cr"
      LINKS_REGISTRY: "https://7egend.cr"

  post-failed-npm-package-notification:
    runs-on: ubuntu-latest
    needs: build-and-publish-npm-package
    if: ${{ always() && needs.build-and-publish-npm-package.result == 'failure' }}
    steps:
      - name: Post failed package build
        run: echo "Failed"