name: Build and deploy server/api docker image

on:
  workflow_dispatch:
  push:
    branches:    
      - main
    tags:
      - '*.*.*'
    paths:
      - 'server/api/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Version Variable
        id: set_version
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "version=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
            echo ${GITHUB_SHA:0:7}
          elif [[ ${{ github.ref }} == refs/tags/* ]]; then
            echo "version=${{ github.ref }}" >> "$GITHUB_OUTPUT"
            echo ${{ github.ref }}
          fi
          
  
  build-image:
    uses: 7egend/workflows/.github/workflows/build-image.yml@main
    permissions: write-all
    secrets: inherit
    with:
      DOCKER_IMAGE_NAME: server/api
      DOCKERFILE_PATH: server/api/Dockerfile
      CONTEXT_PATH: .
      CONTAINER_RELEASE_VERSION: ${{ needs.prepare.outputs.version }}
    needs: prepare


  build-other-images:
    uses: 7egend/workflows/.github/workflows/create-tag-image.yml@main
    permissions: write-all
    secrets: inherit
    strategy:
      matrix:
        contexts: [devops/ansible, server/api]
    with:
      DOCKERFILE_PATH: ${{ matrix.contexts }}/Dockerfile
      DOCKER_IMAGE_NAME: ${{ matrix.contexts }}
      CONTAINER_RELEASE_VERSION: ${{ needs.prepare.outputs.version }}
    needs: [prepare, build-image]


  deploy-production-notification-hub-api:
    uses: 7egend/workflows/.github/workflows/deploy.yml@main
    with:
      DEPLOYER_IMAGE: ghcr.io/${{ github.repository }}/devops/ansible:latest
      PLAYBOOK: playbooks/production/notification-hub/deploy.yaml
      KNOWN_HOSTS_FILE: ${{ vars.KNOWN_HOSTS_FILE }}
      ENVIRONMENT: production
      CONTAINER_RELEASE_VERSION: ${{ needs.prepare.outputs.version }}
    secrets:
      CI_BOT_SSH_PRIVATE_KEY: ${{ secrets.CI_BOT_SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    needs: [prepare, build-other-images]
